apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: book.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-api
                port:
                  number: 80
